### PR TITLE
Merge 3.0.0 into master

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
Should be done after #88 

Will allow localisation PR to work as intended

### CODE REVIEW

**Comment by devforey** [comment]
If I may comment on an issue with this PR, 

Video:
https://drive.google.com/file/d/1tgDjSpDRSzfEMU6wjN2SsArVQ49Ca05x/view?usp=share_link

^As seen in the video, whichever key I pressed first in WASD, that key won't register.

I also tried pointing the PlayTools to https://github.com/PlayCover/PlayTools/pull/88, but the issue isn't resolved.
image

E.g
I press W first then A/S/D, W won't register... and so on.

Please let me know if this isn't the right place to issue this.

**Comment by devforey** [comment]
Additionally, I can't seem to record a new keymap in Keymap Editing Mode.

https://drive.google.com/file/d/1Gdji_d4JN6HTZUndwwUICJHs25Qyvq0B/view?usp=share_link

^As seen in the video, I'm trying to create a new Keymap. In Keymap Editing Mode, I can't seem to change LMB to anything even if I pressed any keys.

**Comment by amirsaam** [comment]
> Additionally, I can't seem to record a new keymap in Keymapping Editor.
> 
> 
> 
> https://drive.google.com/file/d/1Gdji_d4JN6HTZUndwwUICJHs25Qyvq0B/view?usp=share_link
> 
> 
> 
> ^As seen in the video, I'm trying to create a new Keymap. In Keymapping Editor, I can't seem to change LMB to anything even if I pressed any keys.

LMB not changing is intended and it's like this for many years now in PlayCover.

**Comment by devforey** [comment]
> > Additionally, I can't seem to record a new keymap in Keymapping Editor.
> > https://drive.google.com/file/d/1Gdji_d4JN6HTZUndwwUICJHs25Qyvq0B/view?usp=share_link
> > ^As seen in the video, I'm trying to create a new Keymap. In Keymapping Editor, I can't seem to change LMB to anything even if I pressed any keys.
> 
> LMB not changing is intended and it's like this for many years now in PlayCover.

Sorry I might be confused. How would we create a new keymap in-game then?

**Comment by amirsaam** [comment]
Actually, yes.
That is indeed a bug introduced into Keymap editor.
Thanks for pointing out.

**Pull request closed without merging**
