### PR TITLE
Keymapping module architectural refactor

### PR DESCRIPTION
**Pull request by XuYicong**
A giant step towards fixing any keymapping bug, trust me bro(

So finally we have some software diagrams. We have class inheritance graph, state transition graph and data flow diagram. By the way, anyone knows a better diagram tool than a crowded draft paper? 

Data Flow Diagram: (What happens when you press any key in game)
IMG_20230919_071327

Class Inheritance Graph: (Different event adapters for different device and different control mode)
IMG_20230919_071448

State Transition Graph: (Smart Keymapping corresponds to Click state. When that is disabled, only three states: Off, Editor and Camera)
IMG_20230919_071353

### CODE REVIEW

**Review by IsaacMarovitz — APPROVED** [review]
Excellent work as always!

**Review by ohaiibuzzle — APPROVED** [review]
Looks good to me

**Review by JoseMoreville — APPROVED** [review]
Good job xuxy

**Comment by smallrodya** [comment]
How do i Install it? i am beginner, pls help me

**Comment by JoseMoreville** [comment]
Hi @XuYicong you can use excalidraw or tldraw for diagrams. I'm sure both of these tools will be useful for you in the future.

https://www.tldraw.com/

https://excalidraw.com/

**Pull request merged**
