### PR TITLE
Remove `isGame`, remove refresh rate, make M1 Identifier default

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
This ends up implementing everything in #23

### CODE REVIEW

**Comment by KhoraLee** [comment]
Why 0c47f78ba5fa90547e3e0e72c4744dd2d5aea52a commit even exist?
And why not just merge #23 and make other changes

**Comment by IsaacMarovitz** [comment]
> Why [0c47f78](https://github.com/PlayCover/PlayTools/commit/0c47f78ba5fa90547e3e0e72c4744dd2d5aea52a) commit even exist?
> And why not just merge #23 and make other changes

That was an earlier testing commit that I accidentally left on my branch

**Comment by KhoraLee** [comment]
@IsaacMarovitz
First you have to cherry-pick last two commit. There's no need to preserve irrelevant commit to git history.

Second this can be shown as stealing other person's contribution. There is PR that aiming same goal and you already commented on them. If you want to change something more then you have to preserve that PR's commit history by merging PR on GitHub or just merging it locally.

**Comment by IsaacMarovitz** [comment]
> @IsaacMarovitz First you have to cherry-pick last two commit. There's no need to preserve irrelevant commit to git history.
> 
> Second this can be shown as stealing other person's contribution. There is PR that aiming same goal and you also commented on them. If you want to change something more then you have to preserve that PR's commit history by merging PR on GitHub or just merging it locally.

My intention was not to steal your work. I made the changes before releasing you had already PR'd them sorry.

I will remake this PR without the irrelevant commits and using your PR as a base.

**Pull request closed without merging**
