### PR TITLE
Support mapping more keys & fix controller D-Pad input issue in keymap editor

### PR DESCRIPTION
**Pull request by XuYicong**
Can now map more keys on different types of keyboards, including number keypad and function keys up to F20.

Fix controller direction pad issue when setting the key in the keymap editor, where the element has to be unfocused before a D-Pad key is released to be mapped.

Also, testing on an Xbox controller shows the D-Pad up and down key are reversed. They're now swapped back.

截屏2024-06-07 15 01 04

### CODE REVIEW

**Review by Depal1 — APPROVED** [review]
I got to test everything but 
```
gcCode[GCKeyCode.international3.rawValue] = "¥" // IntlYen
        gcCode[GCKeyCode.international1.rawValue] = "ろ" // IntlRo
        gcCode[GCKeyCode.nonUSBackslash.rawValue] = "§" // 100
        gcCode[GCKeyCode.nonUSPound.rawValue] = "Keypad ,"
        gcCode[GCKeyCode.LANG2.rawValue] = "英数 한자" // Eisu(alphanumeric) Hanja
        gcCode[GCKeyCode.LANG1.rawValue] = "かな 한/영" // Kana Korean/English
```
They should be alright though.

**Review by TheMoonThatRises — CHANGES_REQUESTED** [review]
Some of the abbreviations are inconsistant (such as `Delete` vs `Del`). Also might be worth abbreviating other commonly abbreviated words such as `Context` to `Ctx` and `Forward` to `Fwd`. @Depal1?

**Review by Depal1 — COMMENTED** [review]
I agree with the other abbreviations @TheMoonThatRises suggested, but I don't think it is necessary to abbreviate 'page'.

**Comment by XuYicong** [comment]
I was considering a way of decreasing the file length. There are three dicts: `mapVirtualToName`, `mapGCtoName` and `mapVirtualToGc`. Actually `mapVirtualToName` can be generated from the other two dicts during class initialization. In that way we can both shorten the file length and mitigate the risk of data inconsistency when editing these dicts. Do you think it's a good idea?

**Comment by Depal1** [comment]
> I was considering a way of decreasing the file length. There are three dicts: `mapVirtualToName`, `mapGCtoName` and `mapVirtualToGc`. Actually `mapVirtualToName` can be generated from the other two dicts during class initialization. In that way we can both shorten the file length and mitigate the risk of data inconsistency when editing these dicts. Do you think it's a good idea?

By all means, it would be a better approach for the maintainability of the code.

**Review by Depal1 — APPROVED** [review]

**Review by TheMoonThatRises — APPROVED** [review]

**Pull request merged**
