### PR TITLE
Controller Mapping - Part 1

### PR DESCRIPTION
**Pull request by XuYicong**
Addresses #17 

This is the part 1 out of 2, to add support of mapping controller buttons & thumbsticks to touchscreen actions. 

In this part, PlayMice has been refactored to add support of thumbstick mapping. As this refactor changes a lot of how PlayMice works, it would be better to merge this earlier, so as to avoid potential conflicts later.

## What This PR Has Done

 - Mapping thumbsticks to camera control and joystick control and draggable button
 - Mapping controller keys except LS/RS/D-PAD
 - Changed joystick mapping's appearence under editor mode to distinguish with camera control
 - Added new item to circle menu for mouse-controled joystick.
 - Deleted useless circle menu items (aka adding mouse buttons, since mouse buttons can now be added just like other keys)
 - Removed UwU (That event handler is now occupied)

## What Are Left For Part 2

- Sensitivity adjustment of thumbstick mapping
- D-PAD/LS/RS mapping
- Map controller keys to draggable buttons
- Font size of controller keynames should be fixed (some names are too long)
- Bind current configuration "sensitivity" to action's displayed size

### CODE REVIEW

**Comment by amirsaam** [comment]
You are my hero buddy <3

**Comment by amirsaam** [comment]
how can I test it?

**Comment by XuYicong** [comment]
@amirsaam Before you build playcover, in carthage config file, set playtools revision as this branch. Then when you build playcover, it will be built with this branch's playtools.

**Comment by amirsaam** [comment]
@XuYicong sorry I'm not familiar with `carthage`, did I do it wrong?
```
git "https://github.com/XuYicong/PlayTools" "feat/controller-mapping"
```
in `input` file

**Comment by XuYicong** [comment]
@amirsaam I don't mean a `input` file. I mean the `Cartfile` file in root directory of playcover repository.
Change the content of it to `github "XuYicong/PlayTools" "feat/controller-mapping"`

**Comment by amirsaam** [comment]
oh, my bad. didn't pay attention to that. I figured it out with your help.

there are couple of problems:
1. RSB and LSB do not care if the stick returned to original state (and no matter what, any mouse movement would end as keybind like the LMB)
https://user-images.githubusercontent.com/1331289/194232343-5debdb5c-4b14-4ba6-8ba8-dcf8926707bc.mp4
2. D-PAD keys do not answer at all no matter if they are as D-PAD or just individual keys (tbh I duuno if they can work as individual at all because I couldn't test, but if they are not planned like that, they should be)
https://user-images.githubusercontent.com/1331289/194232847-5e33fd51-d8aa-4175-a970-4e4cce2bf5c6.mp4
other keys as far as I tested worked fine.

**Comment by XuYicong** [comment]
> RSB and LSB do not care if the stick returned to original state (and no matter what, any mouse movement would end as keybind like the LMB)

For LSB and RSB mapping, there are two modes. They can be mapped to a mouse area or a joystick. In your case, you should map it to a joystick, rather than mouse area. Mouse area is designed for camera control.

For mouse movement mapping, yes, it becomes keybind once mouse moved. It is currently so designed. Do you have a better idea how should that work?

> D-PAD keys do not answer at all no matter if they are as D-PAD or just individual keys (tbh I duuno if they can work as individual at all because I couldn't test, but if they are not planned like that, they should be)

D-PAD keys are expected to work as individual keys, but they may currently have bugs. But they are not expected to be mapped to WASD control. You can instead map a LSB or RSB to that.

**Comment by amirsaam** [comment]
> LSB and RSB are treated equivalently. Either LSB or RSB can be mapped to Directional Move then should work as Directional Move.

I didn't get this right, so if I map RSB as camera control, what is expected behaviour?

> Good idea. I remember Isaac was making a new editor UI? If he has not given up yet, I think it's better to leave this to his new editor UI.

Yeah I tried to mention his work and tell that exactly but looks like he didn't create a PR yet.

**Comment by XuYicong** [comment]
> I didn't get this right, so if I map RSB as camera control, what is expected behaviour?

RSB then works as camera control.

More specifically, when RSB works as camera control, whenever RSB is not in center, the touch point is moving towards corresponding direction. When RSB is back to center, the touch point stops moving, and releases (lift off, cease pressing).

**Comment by amirsaam** [comment]
I just noticed your branch does not contain AKPlugin, I dunno what's its job so I'm just saying

**Comment by amirsaam** [comment]
Can I ask when (approximately) it will be ready?

**Comment by XuYicong** [comment]
Sorry I have not got time to continue with this recently. If others want to contribute to this, you are free to take it. I will not have time for this again until the end of November.

**Review by Depal1 — APPROVED** [review]
Everything works as stated in the pull request's description. GC buttons can be mapped, including the ones from IOkit devices with a GC wrapper. This was tested for GC controllers too, DS4 and Xbox One. Mouse and keyboard maps were verified to work after the changes.

**Review by Depal1 — COMMENTED** [review]
https://github.com/PlayCover/PlayCover/pull/515/files restores compatibility with PlayTools' keymaps.

**Comment by MemoryYiJun** [comment]
您好 我在使用joystick映射时无法直接触发45°方向

**Comment by XuYicong** [comment]
@MemoryYiJun Hello, I'm not sure what exactly do you mean by "joystick 映射". This PR is about mapping controller（手柄） to touches, but I think you are referring to something related to WASD. If this is the case, re-create the mapping by choosing the approriate mapping type. You can read our [docs](https://docs.playcover.io/getting_started) for detailed guide. If you have more questions you can also join the [discord server](https://discord.com/invite/PlayCover) or QQ群（767242941）for help.

**Pull request merged**
