### PR TITLE
Add missing semicolon in project.pbxproj

### PR DESCRIPTION
**Pull request by Depal1**

### CODE REVIEW

**Review by TheMoonThatRises — APPROVED** [review]

**Comment by XuYicong** [comment]
Is the line `sourceTree = "<group>";` necessary?

**Comment by TheMoonThatRises** [comment]
Yeah, I think so.

**Comment by Depal1** [comment]
It is missing too, I compared it with the original PR.

**Comment by Depal1** [comment]
It should be okay now.

**Review by XuYicong — APPROVED** [review]

**Pull request merged**
